adobe_users:
  exclude_identity_types:
    - adobeID
  connectors:
    umapi: connector-umapi.yml
directory_users:
  user_identity_type: federatedID
  default_country_code: US
  connectors:
    csv: connector-csv.yml
  groups:
limits:
  max_adobe_only_users: 0
