# Sign API Connections
sign_orgs:
  primary: connector-sign.yml
  #secondary: connector-sign.yml

# Similar to "directory_users.connectors" in user-sync-config.yml
identity_source:
  type: ldap
  connector: connector-ldap.yml

# Options that govern the synchronization of users
user_sync:
  sign_only_limit: 100

# User management group/role mappings
user_management:

## TEST 1
    - directory_group: Sign Group 1
      sign_group: Sign Group 1
      group_admin:
      account_admin:

    - directory_group: Sign Admin 2
      group_admin: True


# Logging options
#logging:
#  log_to_file: True
#  file_log_directory: sign_logs
#  file_log_name_format: '{:%Y-%m-%d}-sign.log'
#  file_log_level: debug
#  console_log_level: debug

# Defaults for options that can be passed as CLI options
#invocation_defaults:
#  #users: all
#  test_mode: True
